name: CI With Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources/
          touch ./src/main/resources/application.yml
          echo ${{secrets.APPLICATION_SETTINGS}} | base64 --decode > ./src/main/resources/application.yml

      - name: Make application-secret.yml
        run: |
          mkdir -p ./src/main/resources/
          touch ./src/main/resources/application-secret.yml
          echo ${{secrets.APPLICATION_SECRET}} | base64 --decode > ./src/main/resources/application-secret.yml

      - name: Build with Gradle
        run: |
          chmod 777 ./gradlew
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/jun2_community_be .

      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jun2_community_be:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: Docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jun2_community_be:latest

      - name: Docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      - name: Docker run new container
        run: sudo docker run --rm --name be-server -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/jun2_community_be:latest

      - name: Delete old docker image
        run: sudo docker system prune -f
